
server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:mem:restaurants
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: RESTAURANT-SERVICE

  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: restaurants_1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  #  config:
  #    import: configserver:http://localhost:9296
  h2:
    console:
      enabled: true
  security:
    user:
      name: root
      password: root

auto:
  create:
    topics:
      enable: true

